sudo: false

language: python

python:
  - 2.7
  - 3.5

install:
  - pip install --upgrade pip setuptools
  - pip install -r requirements.txt
  - pip install .

script:
  - cd tests/
  - nosetests --with-coverage --cover-package=openpromela

after_success:
  - coveralls
