sudo: required

language: python

python:
  - 2.7

install:
  - pip install --upgrade pip setuptools
  - pip install -r requirements.txt
  - ./install_slugs.sh
  - pip install .

script:
  - cd tests/
  - nosetests --with-coverage --cover-package=openpromela

after_success:
  - coveralls
